name: AgoraABRAudience
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 15.0
settings:
  base:
    SWIFT_VERSION: 5.9
    PRODUCT_BUNDLE_IDENTIFIER: com.example.AgoraABRAudience
packages:
  AgoraRtcEngine_iOS:
    url: https://github.com/AgoraIO/AgoraRtcEngine_iOS
    from: 4.6.2
targets:
  AgoraABRAudience:
    type: application
    platform: iOS
    dependencies:
      - package: AgoraRtcEngine_iOS
        product: RtcBasic
    sources:
      - path: AgoraABRAudience/Sources
      - path: AgoraABRAudience/Resources
    info:
      path: AgoraABRAudience/Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: Camera access is needed to render and test Agora video.
        NSMicrophoneUsageDescription: Microphone access is needed for Agora audio playback/session setup.
